### ISSUE TITLE
[Question] Is it only for file:// or does it also work with sites in an iframe?

### ISSUE THREAD

**Issue by Tarang** [knowledgecode/WebSocket-for-Android#11]
Does the plugin still work if the index.html file has an iframe in it that connects to a website that uses websockets (via SockJS)?

I'm testing out Meteor apps with Cordova using an Android 4.2.1. I'm curious if this can work with it.

**Comment by SuryaAdabala** [comment]
[Question] I am new to github and I do not know where to ask questions, So I am asking here, help me out on this issue, 

I added WebSocket plugin to my android project and made changes on js file on cordova 3.6.3 and android 4.3, but I am not able to create WebSocket connection.Is there anything I need to add on native side to initiate WebSocket connection.

Thanks in Advance.

**Comment by pawelfus** [comment]
I totally forget about this issue. We resigned from Cordova after all - as for me, ticket can be closed.

**Comment by knowledgecode** [comment]
I'm finally able to close this.

**Comment by pawelfus** [comment]
Yeah, I know that feeling.. Sorry for a delay! :)
