### ISSUE TITLE
org.eclipse.jetty.util.thread package missing

### ISSUE THREAD

**Issue by digigm** [knowledgecode/WebSocket-for-Android#22]
Once installed with 'cordova plugin add com.knowledgecode.cordova.websocket', you get following classes placed in directory that doesn't match its package 'org.eclipse.jetty.util.thread' 
classes affected: QueuedThreadPool, ThreadPool, Timeout.

The project compiles from CLI  and there are correct classes complied under platforms ▸ android ▸ ant-build ▸ classes ▸ org ▸ eclipse ▸ jetty. But the problem is visible under ▸ platforms ▸ android ▸ src ▸ org ▸ eclipse ▸ jetty ▸ util where mentioned classes are placed and thread folder is missing. 

It causes eclipse project errors.  
I am using Mac environment for development.

**Comment by knowledgecode** [comment]
Oh, I see.
I just fixed it. Thank you very much!
