### ISSUE TITLE
Android 4.4 needs override plugin option set to true

### ISSUE THREAD

**Issue by digigm** [knowledgecode/WebSocket-for-Android#23]
After installing plugin and deployment on device with android 4.4 I am getting following error. 

"WebSocket connection to 'ws://xxxxxxxxxxxxx/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received", source: file:///android_asset/www/plugins/com.knowledgecode.cordova.websocket/www/websocket.js (169)

To resolve it I need to set override plugin option to true although  I would prepare platform implementation.

**Comment by knowledgecode** [comment]
Oops! My bad.
Thank you for your report. I just fixed it.
