### ISSUE TITLE
not be able to create WebSocket connection

### ISSUE THREAD

**Issue by knowledgecode** [knowledgecode/WebSocket-for-Android#24]
> [Question] I am new to github and I do not know where to ask questions, So I am asking here, help me out on this issue,
> 
> I added WebSocket plugin to my android project and made changes on js file on cordova 3.6.3 and android 4.3, but I am not able to create WebSocket connection.Is there anything I need to add on native side to initiate WebSocket connection.
> 
> Thanks in Advance.

@SuryaAdabala
Thank you for using this plugin. Your post was moved here.
Now I can't answer your question because of too few clues. Could you paste the code snippet here? What error message are you getting?

**Comment by SuryaAdabala** [comment]
var _socket = new WebSocket(server);
       	_socket.onopen = function(){
           console.log("onopen");   
        };
    
	_socket.onclose = function(mesg) {
             console.log("onclose");   
	};

	_socket.onerror = function(mesg){
             console.log("onerror");   
	};
	    
       _socket.onmessage = function(mesg){
             console.log("onmessage");   
        };
I added the above code on my js file and didn't make any change on native side.
and I got this error "ReferenceError: WebSocket is not defined".

**Comment by knowledgecode** [comment]
Need to wait that "**deviceready**" event fired. Almost plugins cannot be accessed before the event fired. Refer to [the example](https://github.com/knowledgecode/WebSocket-for-Android#websocketurl-protocols) in README.md.

**Comment by SuryaAdabala** [comment]
Thanks for reply, I found issue with related to path for websocket.js on my cordova_plugins.js file.  After setting the path it's working fine. Thanks for giving such a use full plugin.
