### ISSUE TITLE
Rebutting connection every 10 seconds

### ISSUE THREAD

**Issue by imbxl** [knowledgecode/WebSocket-for-Android#25]
Hi, the websocket is rebutting connection every 10 seconds and restarting the handshake.

**Comment by knowledgecode** [comment]
Thank you for using the plugin.

It does not have a feature of auto reconnection. Are you using some sort of library? Also does the same thing occur in browsers that support WebSocket?

**Comment by knowledgecode** [comment]
I'll close this issue because there is no response for a long time. Post here again if you have any problems.
