### ISSUE TITLE
my issue with the websocket-for-android

### ISSUE THREAD

**Issue by 274921407** [knowledgecode/WebSocket-for-Android#27]
hi,
  i  have a  problem:  the  app  in some android device  is running normal,but  "in some devices"(android 4.0.3)  i can conenct normally,receive infomation  from  other people using web normarlly , but  
Failed to send message with "some devices"!
   please help me !  thanks!

my cordova version 5.1.1     ,with cordova   ceate   android project    target android 4.0.2.
if you find the probleam ,send email  for me  .email:274921407@qq.com

**Comment by knowledgecode** [comment]
I have some questions.
- What is the message that failed to send, for example?
- What kind of error occurred?
- Are you using wss protocol?

**Comment by 274921407** [comment]
Hi, I'm surprised, you can reply to email. My problem had solved. We  update the websocket version  in our server. Thanks a lot!
 




------------------ 原始邮件 ------------------
发件人: "KNOWLEDGECODE";<notifications@github.com>;
发送时间: 2015年8月7日(星期五) 中午1:47
收件人: "knowledgecode/WebSocket-for-Android"<WebSocket-for-Android@noreply.github.com>; 
抄送: "℉ōrèvèr"<274921407@qq.com>; 
主题: Re: [WebSocket-for-Android] my issue with the websocket-for-android(#27)




I have some questions.
  
What is the message that failed to send, for example?
 
What kind of error occurred?
 
Are you using wss protocol?
