### ISSUE TITLE
Unescape string in SendingTask before sending it to server

### ISSUE THREAD

**Issue by shilder** [knowledgecode/WebSocket-for-Android#28]
SendingTask.java line 58

```
conn.sendMessage(rawArgs.substring(11, rawArgs.length() - 2));
```

rawArgs contains `JSON.stringify`ed string, which escapes some symbols (specifically double quotes)

You should unescape them before sending it to server.

Something like
```
JSONArray json = new JSONArray(rawArgs);
String str = (String)json.get(0);
conn.sendMessage(str.substring(9, str.length()));
```

**Comment by knowledgecode** [comment]
Sorry for my late response, and thank you for pointing out the bug. I've just fixed it and published as ver.0.11.1.
