### ISSUE TITLE
Error "websocket is not defined"

### ISSUE THREAD

**Issue by hassandad** [knowledgecode/WebSocket-for-Android#29]
I am Developing a hybrid app using phonegap. I developed whole app using browser and run it using apache. I also implemented websocket using html5. Socket works well in browser. For using it native with cordova i used your plugin. But when i try to work with websocket, i get error "Websocket is not defined" on line 
var socket = new WebSocket("ws://localhost:9000/");

What i am doing wrong??? please help me

**Comment by knowledgecode** [comment]
Possible cause of the problem is to fail to install the plugin, or to attempt to touch WebSocket before `deviceready` event is fired.
Please make sure your code is like this:
```javascript
document.addEventListener("deviceready", function () {

    var socket = new WebSocket("ws://localhost:9000/");

    socket.onopen = function () {
        console.log("open");
    };

}, false);
```

**Comment by hassandad** [comment]
My code is inside device ready function and i have tested it. And also plugin get installed successfully and i can see it installed. How could i test if the plugin is installed correctly????  Also i am testing this on the device connected with my computer and device is trying to access locahost running on my computer. What else could be the reason????

**Comment by knowledgecode** [comment]
I don't know about PhoneGap CLI, but in case of Cordova CLI you can make sure that the plugin is installed correctly like this:
```sh
$ cordova plugin
cordova-plugin-websocket 0.12.0 "WebSocket for Android"
```
Anyway, if it has been installed correctly, I guess you have already solved the problem about that error message (`Websocket is not defined`).

Are you testing with an emulator on the computer? The emulator has a different IP address from the computer, so it can't connect to the `localhost`.
```javascript
// rewrite into the computer's private IP address
var socket = new WebSocket("ws://192.168.x.x:9000/");
```

**Comment by hassandad** [comment]
Yep It works now. Thanks a lot dear for helping me.
