### ISSUE TITLE
websocket topic

### ISSUE THREAD

**Issue by alexandraFlavia9** [knowledgecode/WebSocket-for-Android#30]
Hello! 
By using this plugin, is there any possibility to send/receive messages to/from a specific topic after making a connection and subscribing to that topic?

Thanks in advance!

**Comment by knowledgecode** [comment]
What do you mean by that? This plugin does not send/receive any message after connecting by itself. Could you tell me what kind of problems are you having concretely?

**Comment by alexandraFlavia9** [comment]
This is an example of  what I'd want to simulate: http://www.eclipse.org/paho/clients/js/utility/index.html .
After creating a connection, for instance to ws://example.com, to subscribe to a topic and publish messages to that topic.

**Comment by knowledgecode** [comment]
You want to create an app for Android like that site, don't you? In general, yes. Post a message on this board again if you have any problems during creating the app.

Good luck!
