### ISSUE TITLE
wss - goes to onerror after compile

### ISSUE THREAD

**Issue by Jinjos** [knowledgecode/WebSocket-for-Android#31]
Hi,

When trying to run the plugin on wss, the wesocket goes right to on error.

I found in the logcat this message:
**Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.**

Couldn't find any solution to this issue.

Any idea ?

Thanks,
Tomer

**Comment by knowledgecode** [comment]
Check whether the issue is able to reproduce on 4.4+ device. In other words, your app works fine on the built-in WebSocket? If a similar error occurs, the cert might be broken.

**Comment by knowledgecode** [comment]
Since get no response from you, will close. Post here again if you still have any problem.
