### ISSUE TITLE
["CONNECTING", "OPEN", "CLOSING", "CLOSED"] static consts is not defined in WebSocket constructor 

### ISSUE THREAD

**Issue by llevkin** [knowledgecode/WebSocket-for-Android#32]
This consts defined in prototype only, and it break capability for some WebSocket librarys..

**Comment by knowledgecode** [comment]
Thanks for pointing it out. I'll take a look.

**Comment by knowledgecode** [comment]
Just fixed it, and released as v0.12.1. Please make sure the problem is fixed.

**Comment by llevkin** [comment]
Yes, all looks fine now. Thank you!
