### ISSUE TITLE
Unsuccessful Handshake IONIC app with websocket

### ISSUE THREAD

**Issue by vijaykrrao** [knowledgecode/WebSocket-for-Android#33]
Hi,

I have followed your example as described to establish a connection to websocket. Here is the setup, that I have:

Server Side (development):
Tomcat Websocket (javax.websocket v1.1).

Client Side (development):
Ionic v2.0.0
Cordova v6.3.1

When  application is tested on web browser (on desktop), it works well with no issues/errors. However, after the application is built and installed on device. It shows error as following:

**Android 6.0.1**
Immediately on lauch of the app, it hits onerror and shows **"isTrusted":true** followed by **error code 1006**.

**Android 4.4**
![image](https://cloud.githubusercontent.com/assets/8974114/21293763/7afc2e0e-c553-11e6-9532-6a8ff982bd10.png)

Looked up logcat, I notice this 

[INFO:CONSOLE(162)] "WebSocket connection to 'ws://xx.xx.xx.xx:9090/ondemand/retail-orders/11' failed: Error during WebSocket handshake: Unexpected response code: 403", source: file:///android_asset/www/plugins/cordova-plugin-websocket/www/websocket.js (162)

Appreciate if you could please provide pointer/suggestion to overcome this issue faced.

Thanks in advance,
Vijay

**Comment by knowledgecode** [comment]
The 403 error means *"Forbidden"*. Uninstall the websocket plugin and then try again if it is possible. If you get the same error, it is caused by something other than the plugin. For example, does the server check a client origin? When an app is running on Cordova, the origin is usually  `file://`.

**Comment by knowledgecode** [comment]
I'll close this because have no response from you. If you haven't solved this problem yet, can post here again.

**Comment by mukulpatlan** [comment]
Hello,

I am new to websockets and trying to implement it in my Hybrid android app. Although, It works fine while working with http://localhost:8000 but I am getting the following error when I run my Ionic app on the device.

`websocket.js:162 WebSocket connection to 'ws://xxxxxxxxxx' failed: Error during WebSocket handshake: Unexpected response code: 500.`

I am using cookie based authentication with and my backend is in java servlet itself.

Any help would be appreciated.

Thanks

**Comment by knowledgecode** [comment]
To isolate the problem check if it can connect the server without the plugin. If you see the same error, perhaps the plugin has no relation to it.

**Comment by mukulpatlan** [comment]
Thank you for your response. I resolved my error. It was something to do with the server itself.

**Comment by dinesh-krish** [comment]
@mukulpatlan how you fixed?.
