### ISSUE TITLE
Websocket closes with code 1002 on close

### ISSUE THREAD

**Issue by ajsh4u** [knowledgecode/WebSocket-for-Android#34]
On close Web socket receives a 1002 event code. Any help would be appreciated.

**Comment by knowledgecode** [comment]
Is that problem obviously related to this plug in?

The status code of 1002 is a protocol error.  I guess the server expects a client connects to it with sub protocols.  You can specify them at the second parameter of the WebSocket constructor.  Sub protocol is an own agreement between a server and a client in general, so you should ask someone server-side staffs about it.

**Comment by knowledgecode** [comment]
Close this issue since a long time has passed.
