### ISSUE TITLE
Websocket close ifself with code 1005

### ISSUE THREAD

**Issue by Garfielt** [knowledgecode/WebSocket-for-Android#37]
Hi,

I use this plugin in cordova，and found the websocket close itself with 1005，I search the RFC doc it means CLOSE_NO_STATUS, I have realy no means, any help would be appreciated?

This is the event from onclose:
> {"reason":"","code":1005,"wasClean":true,"path":{"length":0},"cancelBubble":false,"returnValue":true,"srcElement":{"binaryType":"blob","protocol":"","extensions":"","bufferedAmount":0,"readyState":3,"url":"ws://192.168.188.20:7001/ws","URL":"ws://192.168.188.20:7001/ws"},"defaultPrevented":false,"timeStamp":1487753895945,"cancelable":false,"bubbles":false,"eventPhase":2,"currentTarget":{"binaryType":"blob","protocol":"","extensions":"","bufferedAmount":0,"readyState":3,"url":"ws://192.168.188.20:7001/ws","URL":"ws://192.168.188.20:7001/ws"},"target":{"binaryType":"blob","protocol":"","extensions":"","bufferedAmount":0,"readyState":3,"url":"ws://192.168.188.20:7001/ws","URL":"ws://192.168.188.20:7001/ws"},"type":"close"}

I sniffer it and find the cordova app close it first:

![image](https://cloud.githubusercontent.com/assets/3894636/23204231/b21098a2-f920-11e6-90ff-e3a2af1d47ee.png)

**Comment by knowledgecode** [comment]
Why don't you uninstall this plugin once and try to test whether the error reproduces? If it reproduces, a server side program might be caused it.

**Comment by Garfielt** [comment]
Thanks for your suggest!
