### ISSUE TITLE
No messeges with multiple instances

### ISSUE THREAD

**Issue by ghost** [knowledgecode/WebSocket-for-Android#38]
Still unable to send and receive messages when there are multiple instances.

**Comment by knowledgecode** [comment]
I could not reproduce the issue.
```
Server s0: open
Server s0: hello
Server s1: error occurred!
Server s2: open
Server s2: hello
```
The `s2` was succeeded even though the `s1` was failed.

The plugin is not used by default if your app is running on Android 4.4 and later. If so, the issue might be unrelated to the plugin. What is version of Android you are testing?

**Comment by gusuni** [comment]
Thank you for looking into this.

With Android 4.4 and later there is no problem as the plugin uses the BuiltinWebSocket. I can connect to multiple servers, reconnect on server restarts and handle server failures.

With Android 4.0.x, 4.1.x, 4.2.x I can only send/receive messages to/from only one **uws** server. If I try to connect to a second server then the client cannot send and receive messages anymore. If the one connected server restarts the plugin cannot send and receive messages as the new connection triggers the problem. 

Note: With ``ws://echo.websocket.org`` works but not with the minimal server side code above, which uses **uws** and it is the needed one.

**Comment by knowledgecode** [comment]
Removed the comments?

**Comment by ghost** [comment]
Yes, removed the sample code as it was not needed any more.

Thanks again.
