### ISSUE TITLE
WebSocket not working

### ISSUE THREAD

**Issue by gvieiradot** [knowledgecode/WebSocket-for-Android#39]
I'm trying:
```
if("WebSocket" in window){
//code here
}else{
//erro here
}
```
Getting error. WebSocket not present in window.

-Cordova version 7.0,1
-Platform: android 6.2.3
-Android 4.1.1 (My device)

**Comment by knowledgecode** [comment]
That code is exactly written in `deviceready` event?

**Comment by gvieiradot** [comment]
Dang, no. It's at Angular `run`.

**Comment by knowledgecode** [comment]
I don't know very much about AngularJS, Cordova plugins will be usually enabled after `deviceready` event is fired:
```JS
document.addEventListener("deviceready", function () {
    if ("WebSocket" in window) {
        // code here
    } else {
        // erro here
    }
}, false);
```
BTW, as you might already know, it seems there is a library called [ngCordova](http://ngcordova.com/), which is to build Cordova mobile apps with AngularJS.
